### ISSUE TITLE
7.5 小节 有一句翻译怪怪的

### ISSUE THREAD

**Issue by fuluwwa** [nervos-community/RFC-CN#12]
这将使得贷款利息更高，并且使得在 NervosDAO 合约中锁定状态，以获得收入更具吸引力。

换成下文，会不会更好点：
这将使得贷款利息更高，并且比起在 NervosDAO 合约中锁定状态以获得收入来得更具吸引力。

**Comment by assemblyers** [comment]
好像还是不够通顺，我们一起再改一下？
