### ISSUE TITLE
第五节 最后一句话

### ISSUE THREAD

**Issue by hujianping** [nervos-community/RFC-CN#16]
这对于以保护资产为重点的「资产存储」平台来说，这是特别重要的，（其中对于网络中的交易使用不总是发生在线下），而是持续占用全球状态的成本。
<----------上面这一句很难读懂，换成下面这样翻译是否会好点呢，不知道我的理解是否正确哈--------->
这对于以保护资产为重点的「资产存储」网络来说，这是特别重要的。这种网络的大部分使用不是交易（大部分使用在线下），而是持续占用全球状态的消耗。

**Comment by kryptohenry** [comment]
而是持续占用全球状态的消耗
-----------------
这一句好像还是有一点怪的～
