### ISSUE TITLE
全球状态

### ISSUE THREAD

**Issue by u2** [nervos-community/RFC-CN#5]
Global State -> 全局状态或者世界状态。

**Comment by ghost** [comment]
`+ 1`
文章整体的观点不统一，有的翻译成全球状态有的翻译成全局状态，建议改成全局状态好一点

**Comment by assemblyers** [comment]
Orangem 欢迎说说整体的观点你哪里不同意，很希望可以听听你的想法
关于世界状态-全局状态，我自己认为全局可能是更好的词，但是世界状态可能是更面向大众的词，两位觉得呢？

**Comment by Virale** [comment]
原文是 Global State，原本翻译为全局状态，但是对于 Permissionless blockchain 它的确是一个「世界状态」，vote for 世界状态

**Comment by ghost** [comment]
https://github.com/nervos-community/RFC-CN/blame/c93e4a31b6fe0a14d99d0ed9934d23be9b29bc29/README.md#L142

https://github.com/nervos-community/RFC-CN/blame/c93e4a31b6fe0a14d99d0ed9934d23be9b29bc29/README.md#L146

这里是全局状态，可能是我习惯于全局状态了。
其他地方写的都是全球状态。

**Comment by Virale** [comment]
我个人觉得两个词都是合适的（没有一个明确的理由去说我必须要用什么词）

关键是我们全文统一就好

**Comment by assemblyers** [comment]
那我们就用全局状态吧

**Comment by ghost** [comment]
#13
