### ISSUE TITLE
6.1 节 第一段 翻译纠正

### ISSUE THREAD

**Issue by hujianping** [nervos-community/RFC-CN#8]
个人认为将下面这段翻译中的"1000 Byte 的单元" 修改为---> "1000 Byte 的Cell"  更为合适一点：

Nervos CKB 的原生代币是 「Common Knowledge Byte」，简称「CK Byte」。 CK Byte 代表 Cell 空间，它们让拥有者能够占用区块链的全球状态。例如，如果 Alice 拥有 1000 个 CK Byte，她可以创建一个空间为 1000 Byte 的单元

**Comment by kryptohenry** [comment]
支持
