### ISSUE TITLE
6.3 小节 二级发行 剩余5%的部分的处理机制

### ISSUE THREAD

**Issue by hujianping** [nervos-community/RFC-CN#9]
最后剩下的 5％ 既没有占用也没有锁币的部分是归交治理机制处理；在治理没有完善的方案前烧掉。
----->
最后剩下的 5％ （既没有占用也没有锁币的部分）由社区通过治理机制进行处理；如果社区未能达成一致方案，这一部分将被销毁。

**Comment by kryptohenry** [comment]
支持你的写法，欢迎PR
